# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d82511a251b3cc266fef7d259efff7a0c2e86f7cc66a766d50f04ce6716ac081a58e08eafe901df6301bdb4d72d172c6674fae4c900323c702850ca89d0049c5

test:
  secret_key_base: 47ec4c76cc04934f471a3d39818f9a92a8f62d9b0b762d11e8e3b50ce5e94d42ba1d7ae3eb6164634da939e871dceefd73dce700463852b2b4f3ee1bbe66ac95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
